### ISSUE TITLE
yandex translator

### ISSUE THREAD

**Issue by dizaina** [KhaledMohamedP/translate-json-object#1]
I would like to use https://www.npmjs.com/package/yandex-translate instead of google translater , do we have any option for it.

**Comment by KhaledMohamedP** [comment]
@dizaina, I am going to start on the implementation soon, will keep you updated via this issue #1 ;)

**Comment by KhaledMohamedP** [comment]
Thanks for the request. It is ready now `v2.1.0`
https://www.npmjs.com/package/translate-json-object
