### ISSUE TITLE
node server is hanged

### ISSUE THREAD

**Issue by KSelvaraj-Augment** [KhaledMohamedP/translate-json-object#11]
Hello,

I ran translate API background process, which means I sent a response to the user then I triggered a translate function.

If I make a new API call the server not responding.

`router.post('/translateSpainsh', function (req, res) { 
    var survey_structure = req.body.survey_structure;
    var survey_id =  req.body.survey_id;
    var dataStruc ={
        survey_structure:survey_structure
    }
    transalteSurvey(dataStruc,survey_id);

});

function  transalteSurvey(dataItem,surveyId)
 {
    var sync = true;
    TJO.init({
        googleApiKey: 'test_key'
    });
     var  surveyObj =  JSON.parse(dataItem.survey_structure);
    TJO.translate(surveyObj, 'es')
        .then(function (data) {
            var surveyData = {
                survey_structure_es:JSON.stringify(data),
                translate_status:1
            }
           var sql = "UPDATE survey SET ? WHERE id = " + surveyId;
           connection.query(sql, [surveyData], function (err, results) {
               if (err) { console.log(err);  }
           });
            //  sync = false;
        }).catch(function (err) {
            console.log('error ', err)
            var surveyData = {
                translate_status:0
            }
           var sql = "UPDATE survey SET ? WHERE id = " + surveyId;
           connection.query(sql, [surveyData], function (err, results) {
               if (err) { console.log(err);  }
               else {
                   console.log(' some Network error');
               }
           });
});
}`

Thanks in advance!

**Comment by KhaledMohamedP** [comment]
Hello @KSelvaraj-Augment, 

It looks like you are not calling `res.send` nor `res.json` to resolve the request. Also you need to add `try & catch` around the `JSON.parse` operation to avoid crashing the application. 

Please send any errors related to the module here, so we can further debug this issue.

Best of luck!

**Comment by KSelvaraj-Augment** [comment]
Hello @KhaledMohamedP ,


Thanks for your reply.

I already tried above the methods but no luck.

The actual problem is when sending large data to google translate API it will take maximum 2 min (For my JSON) to respond. In this time other users requests are pending till translate is completed

I assume your npm package is having a long loop for splitting the string from JSON object to translate, that's the reason for blocking other user's request.
