### ISSUE TITLE
Bug with yandex and en to ru translation (when special chars is exist)

### ISSUE THREAD

**Issue by iMaximal** [KhaledMohamedP/translate-json-object#17]
Hi!
Thanks you for package.

There is error when I try to translate from EN to RU using yandex api.
(in the same time from en to es correct)

example:
`{
   "messages": {
        "specialCharacters": "Field blablabla ('), dashes (-), periods (.), and spaces ( )",
        "alphanumSpecialCharacters": "Field blablabla ('), dashes (-), periods (.), and spaces ( )",
....
}`

Result: that two lines concatenate to one, third line contains value of 4th line, etc.

**Comment by KhaledMohamedP** [comment]
hi @iMaximal can you please show an example so I can reproduce the issue in my end?

**Comment by iMaximal** [comment]
`{
    "titles": {
        "contactInfo": "Contact Information",
    },
    "messages": {
        "specialCharacters": "Field can only contain special characters apostrophes ('), dashes (-), periods (.), and spaces ( )",
        "alphanumSpecialCharacters": "Field can only contain letters, numbers, and special characters apostrophes ('), dashes (-), periods (.), and spaces ( )",
        "addressErrorMessage": "Please enter an Address",
    },

}`

**Comment by KhaledMohamedP** [comment]
@iMaximal I do see the error now 😞  I think this issue is related to the fix in this PR here https://github.com/KhaledMohamedP/translate-json-object/pull/15

I tried using `os.EOL` as the hash simple and it looks like it fixed it! 

```
var os = require('os');

var hashSimple =os.EOL;
```

I am thinking this will be a good fix, unless you see an issue with this solution :| 

Thanks!

**Comment by iMaximal** [comment]
Great!
Please, add tests to fix reproduce this bug.
Let me know when it will be fixed.
