### ISSUE TITLE
use async/await

### ISSUE THREAD

**Issue by obhakim** [KhaledMohamedP/translate-json-object#19]
Hi, i want to use async/await instead of  TJO.translate(example, 'es')
    .then(function(data) {
      console.log(data);
    }).catch(function(err) {
      console.log('error ', err)
    });

**Comment by KhaledMohamedP** [comment]
Hi @obhakim 

You should be able to use async/await without any problems!


```js
(async () => {
	try {
		const data = await TJO.translate(example, "ru");
		console.log(data);
	} catch (err) {
		console.log("error ", err);
	}
})();
```
