### ISSUE TITLE
Specify values to omit

### ISSUE THREAD

**Issue by Andrei1911** [KhaledMohamedP/translate-json-object#20]
I think it would be great if you could add an array of variable names that this should omit and let with the existing language, Ex: i have a JSON and the first few variables are things i will always need in english,

**Comment by danielcollettepb** [comment]
I also have the case of dates where additional spacing is added. Would be great to have an exclusion/omit list of keys.

**Input**
```
{
    "createdDate": "2019-08-09T10:26:41.000Z",
    "lastModified": "2019-09-10T12:16:51.000Z",
}
```

**Output** (incorrect spacing added)
```
{
      "createdDate": "2019-08-09T10: 26: 41.000Z",
      "lastModified": "2019-09-10T12: 16: 51.000Z",
}
```
