### ISSUE TITLE
Translation of boolean datatype

### ISSUE THREAD

**Issue by Aman-Sahota** [KhaledMohamedP/translate-json-object#31]
TJO is translating boolean present in an array.

**Comment by KhaledMohamedP** [comment]
@Aman-Sahota thanks for reporting this issue. It sounds like a legitimate bug. Would you please add more information such as the service used (google vs yandex) and node.js version ...etc this will help debug this issue easier 😉 

Thank you again 👍

**Comment by KhaledMohamedP** [comment]
I just tested this today and it doesn't seem to be translating booleans in the latest package version. 
Feel free to reopen the issue if still present
